### PR TITLE
 Add ADR usage information. Please refer to guides-9 issue for details.

### PR DESCRIPTION
**Pull request by osmandin**
**What does this PR do?**
Add ADR information to the guides documentation.

**Context**

There's an open ticket for standardizing or documenting ADR usage. I'm also trying to think about the minimal information that should be included in an ADR (and some broader guidelines). This is an initial attempt at discussion with other stakeholders.

**Relevant Tickets**

https://github.com/MITLibraries/guides/issues/9

### CODE REVIEW

**Review by hakbailey — COMMENTED** [review]
This looks good, the only thing I might add is that we've been using [adr-tools](https://github.com/npryce/adr-tools) to create standardized ADRs across our repos. I know it's in the list of tools on the linked page, but linking directly to it here could also be useful for devs getting started with ADRs.

**Comment by osmandin** [comment]
@hakbailey I've updated the ADR to add link to adr-tools. Thanks.

**Comment by osmandin** [comment]
@hakbailey Hi Helen, Any concerns about this, or is it okay merge at this point? Thanks.

**Review by hakbailey — APPROVED** [review]

**Comment by hakbailey** [comment]
Nope, looks good to me!

**Pull request merged**
